ice4j {
  ice {
    termination-delay = 1 hour
  }

  harvest {
    use-ipv6 = false
    use-link-local-addresses = false
    timeout = 3 seconds

    mapping {
      aws {
        enabled = false
      }
    }
  }
}
